#钱包相关配置选项
wallet:
  coin-name: ETH
  block-slot: 1
  block-scan-fixed-delay: 10000  #ms
  recharge-all:
    need: true  #默认不需要汇总
    need-recharge-fee: true #默认不需要打邮费

#web3j配置
web3j:
  endpoint: https://ropsten.infura.io/YKZGQG2QTBx0tiWoB2IF

spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://exchange-mysql:3306/exchange-wallet?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password: